/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Shipping } from "./Shipping";
import { ShippingCountArgs } from "./ShippingCountArgs";
import { ShippingFindManyArgs } from "./ShippingFindManyArgs";
import { ShippingFindUniqueArgs } from "./ShippingFindUniqueArgs";
import { DeleteShippingArgs } from "./DeleteShippingArgs";
import { ShippingService } from "../shipping.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Shipping)
export class ShippingResolverBase {
  constructor(
    protected readonly service: ShippingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Shipping",
    action: "read",
    possession: "any",
  })
  async _shippingsMeta(
    @graphql.Args() args: ShippingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Shipping])
  @nestAccessControl.UseRoles({
    resource: "Shipping",
    action: "read",
    possession: "any",
  })
  async shippings(
    @graphql.Args() args: ShippingFindManyArgs
  ): Promise<Shipping[]> {
    return this.service.shippings(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Shipping, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Shipping",
    action: "read",
    possession: "own",
  })
  async shipping(
    @graphql.Args() args: ShippingFindUniqueArgs
  ): Promise<Shipping | null> {
    const result = await this.service.shipping(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Shipping)
  @nestAccessControl.UseRoles({
    resource: "Shipping",
    action: "delete",
    possession: "any",
  })
  async deleteShipping(
    @graphql.Args() args: DeleteShippingArgs
  ): Promise<Shipping | null> {
    try {
      return await this.service.deleteShipping(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
